spring:
  datasource:
    url: jdbc:mysql://localhost:3307/content_center?nullCatalogMeansCurrent=true&serverTimezone=UTC
    hikari:
      username: root
      password: 123456
      # >= 6.x com.mysql.cj.jdbc.Driver
      # >= 5.x com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
server:
  port: 9090

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    com.frontlinerlzx.contentcenter.feighclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      default:
        loggerLevel: full
