spring:
  datasource:
    url: jdbc:mysql://localhost:3307/content_center?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 123456
      # >= 6.x com.mysql.cj.jdbc.Driver
      # >= 5.x com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8082
